table technical_nse_RSI_calculation
	lineageTag: ce892517-2393-4150-9dc5-490057cebabe

	column ticker
		dataType: string
		lineageTag: 907359a0-2885-4197-8db6-e494e2c20b7f
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column trading_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 801bad28-cefa-4a58-8445-d0ddbc26f408
		summarizeBy: none
		sourceColumn: trading_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column RSI
		dataType: double
		lineageTag: 5979ebf1-32b5-4aef-8824-c52f2312bdc1
		summarizeBy: sum
		sourceColumn: RSI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition technical_nse_RSI_calculation = m
		mode: import
		queryGroup: technical_data_tables
		source = ```
				let
				    Source = Sql.Database("localhost\mssqlserver01", "stockdata_db"),
				    dbo_nasdaq_100_atr = Source{[Schema="dbo",Item="nse_500_RSI_calculation"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(#"dbo_nasdaq_100_atr", each 
				        Date.IsInPreviousNDays([trading_date], 30) or 
				        Date.IsInCurrentDay([trading_date])
				    )
				
				in
				    #"Filtered Rows"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

