table technical_forex_ema_sma_view
	lineageTag: a1d252a5-4b29-47a8-973b-a76f49bd60ea

	column symbol
		dataType: string
		lineageTag: 452961a4-ddcb-4458-8a65-5a1fe312b5f9
		summarizeBy: none
		sourceColumn: symbol

		annotation SummarizationSetBy = Automatic

	column trading_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 6c87853e-8836-4fdb-aded-b07ff0f7e23f
		summarizeBy: none
		sourceColumn: trading_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column close_price
		dataType: double
		lineageTag: a652ce90-0824-443b-b083-4b13d8e3f67a
		summarizeBy: sum
		sourceColumn: close_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SMA_50
		dataType: double
		lineageTag: ebf58289-ff4a-4d9a-9832-b937e2bce4c7
		summarizeBy: sum
		sourceColumn: SMA_50

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SMA_20
		dataType: double
		lineageTag: efda3061-6aa0-4242-8c90-cc2a48418d5f
		summarizeBy: sum
		sourceColumn: SMA_20

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EMA_200
		dataType: double
		lineageTag: 7a024a15-02ec-49df-bc2e-837c5ebf9f27
		summarizeBy: sum
		sourceColumn: EMA_200

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EMA_100
		dataType: double
		lineageTag: 0fabcf20-aba3-4f09-85fc-9efae5e948b9
		summarizeBy: sum
		sourceColumn: EMA_100

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EMA_50
		dataType: double
		lineageTag: ec6570f8-e9b8-410b-a38f-2ad84163dd5c
		summarizeBy: sum
		sourceColumn: EMA_50

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EMA_20
		dataType: double
		lineageTag: c9f1f6a6-b919-417c-91bb-be09e5af291e
		summarizeBy: sum
		sourceColumn: EMA_20

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Trend_Status
		dataType: string
		lineageTag: 510e6b52-e643-4ab9-adeb-4fe59185fe32
		summarizeBy: none
		sourceColumn: Trend_Status

		annotation SummarizationSetBy = Automatic

	column SMA_Cross_Status
		dataType: string
		lineageTag: b7db21a1-aacd-48a0-be08-87d36f2225d5
		summarizeBy: none
		sourceColumn: SMA_Cross_Status

		annotation SummarizationSetBy = Automatic

	partition technical_forex_ema_sma_view = m
		mode: import
		queryGroup: technical_data_tables
		source = ```
				let
				    Source = Sql.Database("localhost\mssqlserver01", "stockdata_db"),
				    dbo_nasdaq_100_atr = Source{[Schema="dbo",Item="forex_ema_sma_view"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(#"dbo_nasdaq_100_atr", each 
				        Date.IsInPreviousNDays([trading_date], 30) or 
				        Date.IsInCurrentDay([trading_date])
				    )
				
				in
				    #"Filtered Rows"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

