table technical_forex_rsi_signals
	lineageTag: 0c7d9fd9-a03c-45ff-8da7-3e365dd0987c

	column symbol
		dataType: string
		lineageTag: 7a2896fb-73b1-44ed-b7a6-9c895e6f2663
		summarizeBy: none
		sourceColumn: symbol

		annotation SummarizationSetBy = Automatic

	column trading_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: dd9164fc-ec4c-41e5-8c7b-877befe75dc3
		summarizeBy: none
		sourceColumn: trading_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column RSI
		dataType: double
		lineageTag: 18e884a1-4fa2-48df-b8e1-1527bc68178b
		summarizeBy: sum
		sourceColumn: RSI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rsi_trade_signal
		dataType: string
		lineageTag: 1291964d-daa8-43f7-9ce4-8d0fffc79a2c
		summarizeBy: none
		sourceColumn: rsi_trade_signal

		annotation SummarizationSetBy = Automatic

	partition technical_forex_rsi_signals = m
		mode: import
		queryGroup: technical_data_tables
		source = ```
				let
				    Source = Sql.Database("localhost\mssqlserver01", "stockdata_db"),
				    dbo_nasdaq_100_atr = Source{[Schema="dbo",Item="forex_rsi_signals"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(#"dbo_nasdaq_100_atr", each 
				        Date.IsInPreviousNDays([trading_date], 30) or 
				        Date.IsInCurrentDay([trading_date])
				    )
				
				in
				    #"Filtered Rows"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

