table technical_nasdaq_100_bollingerband
	lineageTag: 3741d92a-2a65-47ee-b8f6-6d217caf7d76

	column ticker
		dataType: string
		lineageTag: 0efe8c40-9b21-498b-91c0-508be36545a8
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column trading_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 9d2f26ef-3c18-4dea-8b83-f5bb6018c692
		summarizeBy: none
		sourceColumn: trading_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column close_price
		dataType: double
		lineageTag: d8dfa8b5-c298-4a6f-bcf1-e533285aada6
		summarizeBy: sum
		sourceColumn: close_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SMA_20
		dataType: double
		lineageTag: a66cbaec-53aa-4610-a5b1-5278fac31d36
		summarizeBy: sum
		sourceColumn: SMA_20

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Upper_Band
		dataType: double
		lineageTag: 046a1cd9-6f4a-417c-873a-dbf3aac2ce2f
		summarizeBy: sum
		sourceColumn: Upper_Band

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Lower_Band
		dataType: double
		lineageTag: 6aea1b4e-1936-4d8e-86f8-aa2291eb150e
		summarizeBy: sum
		sourceColumn: Lower_Band

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition technical_nasdaq_100_bollingerband = m
		mode: import
		queryGroup: technical_data_tables
		source = ```
				let
				    Source = Sql.Database("localhost\mssqlserver01", "stockdata_db", [Query="
				        SELECT * 
				        FROM nasdaq_100_bollingerband 
				        WHERE trading_date >= DATEADD(day, -30, CAST(GETDATE() AS DATE)) 
				          AND trading_date <= GETDATE()+1
				    "]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"trading_date", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

