table technical_forex_macd_signals
	lineageTag: 80a3a649-27d3-467c-9104-7c8697d54cfc

	column symbol
		dataType: string
		lineageTag: e81b0997-290c-4781-ac04-7aab7a576c74
		summarizeBy: none
		sourceColumn: symbol

		annotation SummarizationSetBy = Automatic

	column trading_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 10692a85-59a6-4d97-9747-fbfae11dac97
		summarizeBy: none
		sourceColumn: trading_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column MACD
		dataType: double
		lineageTag: 4224ed34-9b96-449d-b8c2-ce33cfca68b7
		summarizeBy: sum
		sourceColumn: MACD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Signal_Line
		dataType: double
		lineageTag: fdf11127-3aef-4bc4-b78f-6c90c6785d9f
		summarizeBy: sum
		sourceColumn: Signal_Line

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Histogram
		dataType: double
		lineageTag: dfc34573-978b-470b-903d-dfd4656756fb
		summarizeBy: sum
		sourceColumn: Histogram

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column macd_trade_signal
		dataType: string
		lineageTag: 420f9a83-98fe-41e0-a266-bdbe74997472
		summarizeBy: none
		sourceColumn: macd_trade_signal

		annotation SummarizationSetBy = Automatic

	partition technical_forex_macd_signals = m
		mode: import
		queryGroup: technical_data_tables
		source = ```
				let
				    Source = Sql.Database("localhost\mssqlserver01", "stockdata_db", [Query="
				        SELECT * 
				        FROM forex_macd_signals
				        WHERE trading_date >= DATEADD(day, -30, CAST(GETDATE() AS DATE)) 
				          AND trading_date <= GETDATE()+1
				    "]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"trading_date", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

