table technical_forex_bb_signals
	lineageTag: 7b847b5d-d019-4c7d-9cfc-06adac7f9349

	column symbol
		dataType: string
		lineageTag: a404c5d4-f2b8-4b43-b73b-4b7efcf306d1
		summarizeBy: none
		sourceColumn: symbol

		annotation SummarizationSetBy = Automatic

	column trading_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 60e49099-564e-48e5-b639-5993f66a3663
		summarizeBy: none
		sourceColumn: trading_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column close_price
		dataType: double
		lineageTag: de144a02-ccdd-455b-88da-65e9935d80c9
		summarizeBy: sum
		sourceColumn: close_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SMA_20
		dataType: double
		lineageTag: f0566333-7ff9-4830-b1ef-3eeefd3ff1e1
		summarizeBy: sum
		sourceColumn: SMA_20

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Upper_Band
		dataType: double
		lineageTag: 1cd5bef4-e1b9-4506-977b-4bff96931148
		summarizeBy: sum
		sourceColumn: Upper_Band

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Lower_Band
		dataType: double
		lineageTag: 5bdbbd63-ac01-40a0-924f-8cf2f7881c5a
		summarizeBy: sum
		sourceColumn: Lower_Band

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bb_trade_signal
		dataType: string
		lineageTag: 99809efd-c133-4fa6-b76a-a8a4238c3772
		summarizeBy: none
		sourceColumn: bb_trade_signal

		annotation SummarizationSetBy = Automatic

	partition technical_forex_bb_signals = m
		mode: import
		queryGroup: technical_data_tables
		source = ```
				let
				    Source = Sql.Database("localhost\mssqlserver01", "stockdata_db"),
				    dbo_nasdaq_100_atr = Source{[Schema="dbo",Item="forex_bb_signals"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(#"dbo_nasdaq_100_atr", each 
				        Date.IsInPreviousNDays([trading_date], 30) or 
				        Date.IsInCurrentDay([trading_date])
				    )
				
				in
				    #"Filtered Rows"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

