table technical_forex_atr
	lineageTag: 4a3382fa-eb68-4dd1-822a-e4a822f5b6c8

	column symbol
		dataType: string
		lineageTag: d832ba68-372e-4668-ac9f-f3ec028d3d41
		summarizeBy: none
		sourceColumn: symbol

		annotation SummarizationSetBy = Automatic

	column trading_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: e101d088-d348-4fb3-a04f-9830ba0b806a
		summarizeBy: none
		sourceColumn: trading_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ATR_14
		dataType: double
		lineageTag: c3ba846c-a542-4559-8fb6-b8a6c6944405
		summarizeBy: sum
		sourceColumn: ATR_14

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition technical_forex_atr = m
		mode: import
		queryGroup: technical_data_tables
		source = ```
				let
				    Source = Sql.Database("localhost\mssqlserver01", "stockdata_db", [Query="
				        SELECT * 
				        FROM forex_atr 
				        WHERE trading_date >= DATEADD(day, -30, CAST(GETDATE() AS DATE)) 
				          AND trading_date <= GETDATE()+1
				    "]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"trading_date", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

