table technical_nse_atr
	lineageTag: 1fa4a883-5db8-4e80-864f-f3e9a36f3966

	column ticker
		dataType: string
		lineageTag: 777fea64-cc8d-4ee5-b24f-667248f00fcd
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column trading_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 6b9a9190-d0bf-4d65-be1c-95bb449578c9
		summarizeBy: none
		sourceColumn: trading_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ATR_14
		dataType: double
		lineageTag: 8f3c291c-0593-4d9b-8f23-cf4105e9bc91
		summarizeBy: sum
		sourceColumn: ATR_14

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition technical_nse_atr = m
		mode: import
		queryGroup: technical_data_tables
		source = ```
				let
				    Source = Sql.Database("localhost\mssqlserver01", "stockdata_db", [Query="
				        SELECT * 
				        FROM nse_500_atr 
				        WHERE trading_date >= DATEADD(day, -30, CAST(GETDATE() AS DATE)) 
				          AND trading_date <= GETDATE()+1
				    "]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"trading_date", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

