table technical_forex_atr_spikes
	lineageTag: dd94aac1-eed0-477e-a830-8d26511789f3

	column symbol
		dataType: string
		lineageTag: 491bb268-ebec-4afe-93cc-10ed689f810e
		summarizeBy: none
		sourceColumn: symbol

		annotation SummarizationSetBy = Automatic

	column trading_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: a5c04202-b6ab-4fbe-a66d-e5496360395e
		summarizeBy: none
		sourceColumn: trading_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ATR_14
		dataType: double
		lineageTag: 5c3a271a-e6b4-4358-9fe1-ca3c2ca5c346
		summarizeBy: sum
		sourceColumn: ATR_14

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column atr_volatility_signal
		dataType: string
		lineageTag: aaaabf18-2509-4559-a2e1-28428aba694d
		summarizeBy: none
		sourceColumn: atr_volatility_signal

		annotation SummarizationSetBy = Automatic

	partition technical_forex_atr_spikes = m
		mode: import
		queryGroup: technical_data_tables
		source = ```
				let
				    Source = Sql.Database("localhost\mssqlserver01", "stockdata_db", [Query="
				        SELECT * 
				        FROM forex_atr_spikes
				        WHERE trading_date >= DATEADD(day, -30, CAST(GETDATE() AS DATE)) 
				          AND trading_date <= GETDATE()+1
				    "]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"trading_date", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

